import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { AtlasWiki, actorFromId } from "../sdk/atlas-wiki.js";
export const atlasWikiToolNames = ["atlas_wiki.search", "atlas_wiki.fetch", "atlas_wiki.context_pack", "atlas_wiki.explain_citation", "atlas_wiki.check_freshness", "atlas_wiki.find_owner", "atlas_wiki.find_conflicts", "atlas_wiki.list_sources", "atlas_wiki.validate_access", "atlas_wiki.propose_claim", "atlas_wiki.propose_update", "atlas_wiki.propose_deprecate", "atlas_wiki.report_conflict", "atlas_wiki.ingest", "atlas_wiki.rebuild_index", "atlas_wiki.validate", "atlas_wiki.audit_report", "atlas_wiki.backup_create", "atlas_wiki.backup_verify", "atlas_wiki.connector_status"] as const;
function jsonResult(value: unknown) { return { content: [{ type: "text" as const, text: JSON.stringify(value, null, 2) }], structuredContent: value as Record<string, unknown> }; }
export function createAtlasWikiMcpServer(options: { root?: string } = {}): McpServer {
  const server = new McpServer({ name: "atlas-wiki", version: "0.1.0" });
  server.registerTool("atlas_wiki.search", { title: "Atlas WiKi Search", description: "ACL-filtered lexical search.", inputSchema: { query: z.string(), root: z.string().optional(), as: z.string().optional(), limit: z.number().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const results = await wiki.search(input.query, actorFromId(input.as), input.limit); await wiki.close(); return jsonResult(results); });
  server.registerTool("atlas_wiki.fetch", { title: "Atlas WiKi Fetch", description: "Fetch an allowed record.", inputSchema: { id: z.string(), root: z.string().optional(), as: z.string().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const result = await wiki.fetch(input.id, actorFromId(input.as)); await wiki.close(); return jsonResult(result ?? null); });
  server.registerTool("atlas_wiki.context_pack", { title: "Atlas WiKi Context Pack", description: "Build ACL-filtered citation evidence.", inputSchema: { query: z.string(), root: z.string().optional(), as: z.string().optional(), limit: z.number().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const pack = await wiki.contextPack(input.query, actorFromId(input.as), input.limit); await wiki.close(); return jsonResult(pack); });
  server.registerTool("atlas_wiki.propose_claim", { title: "Atlas WiKi Propose Claim", description: "Create a pending claim proposal.", inputSchema: { text: z.string(), root: z.string().optional(), source_id: z.string().optional(), as: z.string().optional(), owner: z.string().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const proposal = await wiki.proposeClaim({ text: input.text, source_id: input.source_id, requested_by: actorFromId(input.as), owner: input.owner }); await wiki.close(); return jsonResult(proposal); });
  server.registerTool("atlas_wiki.validate", { title: "Atlas WiKi Validate", description: "Validate schema and audit chain.", inputSchema: { root: z.string().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const validation = await wiki.validate(); await wiki.close(); return jsonResult(validation); });
  server.registerTool("atlas_wiki.ingest", { title: "Atlas WiKi Ingest", description: "Ingest trusted text into the local wiki.", inputSchema: { title: z.string(), text: z.string(), root: z.string().optional(), owner: z.string().optional(), visibility: z.enum(["public", "internal", "private"]).optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const source = await wiki.ingestText({ title: input.title, text: input.text, owner: input.owner, visibility: input.visibility }); await wiki.close(); return jsonResult(source); });
  server.registerTool("atlas_wiki.rebuild_index", { title: "Atlas WiKi Rebuild Index", description: "Rebuild the FTS projection.", inputSchema: { root: z.string().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); wiki.store.rebuildIndex(); await wiki.close(); return jsonResult({ ok: true, rebuilt: "chunks_fts" }); });
  server.registerTool("atlas_wiki.backup_create", { title: "Atlas WiKi Backup Create", description: "Create a WAL-safe SQLite backup.", inputSchema: { root: z.string().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const path = await wiki.store.backupCreate(); await wiki.close(); return jsonResult({ ok: true, path }); });
  server.registerTool("atlas_wiki.backup_verify", { title: "Atlas WiKi Backup Verify", description: "Verify backup files restore with core tables.", inputSchema: { root: z.string().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const result = wiki.store.backupVerify(); await wiki.close(); return jsonResult(result); });
  server.registerTool("atlas_wiki.list_sources", { title: "Atlas WiKi List Sources", description: "List readable sources for an actor.", inputSchema: { root: z.string().optional(), as: z.string().optional(), query: z.string().optional(), limit: z.number().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const results = await wiki.search(input.query ?? "", actorFromId(input.as), input.limit ?? 50); await wiki.close(); return jsonResult(results.map((result) => result.source)); });
  server.registerTool("atlas_wiki.check_freshness", { title: "Atlas WiKi Check Freshness", description: "Return freshness markers for readable evidence.", inputSchema: { root: z.string().optional(), as: z.string().optional(), query: z.string().optional(), limit: z.number().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const pack = await wiki.contextPack(input.query ?? "", actorFromId(input.as), input.limit); await wiki.close(); return jsonResult(pack.freshness_markers); });
  server.registerTool("atlas_wiki.find_conflicts", { title: "Atlas WiKi Find Conflicts", description: "Return conflict markers for readable evidence.", inputSchema: { root: z.string().optional(), as: z.string().optional(), query: z.string().optional(), limit: z.number().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const pack = await wiki.contextPack(input.query ?? "", actorFromId(input.as), input.limit); await wiki.close(); return jsonResult(pack.conflict_markers); });
  server.registerTool("atlas_wiki.find_owner", { title: "Atlas WiKi Find Owner", description: "Find owners for readable sources.", inputSchema: { root: z.string().optional(), as: z.string().optional(), query: z.string().optional(), limit: z.number().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const results = await wiki.search(input.query ?? "", actorFromId(input.as), input.limit ?? 20); await wiki.close(); return jsonResult(results.map((result) => ({ source_id: result.source.id, title: result.source.title, owner: result.source.owner ?? null }))); });
  server.registerTool("atlas_wiki.explain_citation", { title: "Atlas WiKi Explain Citation", description: "Return citation details from a context pack.", inputSchema: { root: z.string().optional(), as: z.string().optional(), query: z.string(), citation_id: z.string().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const pack = await wiki.contextPack(input.query, actorFromId(input.as)); await wiki.close(); return jsonResult(input.citation_id ? pack.citations.filter((citation) => citation.id === input.citation_id) : pack.citations); });
  server.registerTool("atlas_wiki.validate_access", { title: "Atlas WiKi Validate Access", description: "Validate read access without disclosing denied content.", inputSchema: { id: z.string(), root: z.string().optional(), as: z.string().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const record = await wiki.fetch(input.id, actorFromId(input.as)); await wiki.close(); return jsonResult({ id: input.id, allowed: Boolean(record) }); });
  for (const name of ["atlas_wiki.propose_update", "atlas_wiki.propose_deprecate", "atlas_wiki.report_conflict"] as const) {
    server.registerTool(name, { title: name, description: "Create a pending write proposal.", inputSchema: { text: z.string(), root: z.string().optional(), source_id: z.string().optional(), as: z.string().optional(), owner: z.string().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const type = name === "atlas_wiki.propose_update" ? "update" : name === "atlas_wiki.propose_deprecate" ? "deprecate" : "conflict"; const proposal = await wiki.proposeChange(type, { text: input.text, source_id: input.source_id, requested_by: actorFromId(input.as), owner: input.owner }); await wiki.close(); return jsonResult(proposal); });
  }
  server.registerTool("atlas_wiki.audit_report", { title: "Atlas WiKi Audit Report", description: "Run validation and return audit-chain findings.", inputSchema: { root: z.string().optional() } }, async (input) => { const wiki = await AtlasWiki.open({ root: input.root ?? options.root }); const validation = await wiki.validate(); await wiki.close(); return jsonResult({ ok: validation.ok, findings: validation.findings.filter((finding) => finding.startsWith("audit_")) }); });
  server.registerTool("atlas_wiki.connector_status", { title: "Atlas WiKi Connector Status", description: "Return core connector capability status.", inputSchema: { root: z.string().optional() } }, async () => jsonResult({ ok: true, connectors: [], core_imports_connector_sdks: false }));
  return server;
}
export async function startStdioMcpServer(options: { root?: string } = {}): Promise<void> { const server = createAtlasWikiMcpServer(options); await server.connect(new StdioServerTransport()); }
