create table if not exists atlas_wiki.audit_events (
  id text primary key,
  seq bigint generated by default as identity,
  event_type text not null,
  actor_json jsonb not null,
  request_id text,
  record_refs_json jsonb not null,
  policy_decisions_json jsonb not null,
  outcome text not null check (outcome in ('success', 'denied', 'error')),
  created_at timestamptz not null,
  hash_prev text,
  hash_self text not null
);

alter table atlas_wiki.audit_events enable row level security;
alter table atlas_wiki.audit_events force row level security;

grant insert on atlas_wiki.audit_events to authenticated;

create policy "audit append only authenticated"
on atlas_wiki.audit_events for insert
to authenticated
with check (actor_json ? 'id' and outcome in ('success', 'denied', 'error'));

create index if not exists idx_atlas_audit_events_seq on atlas_wiki.audit_events(seq);
create index if not exists idx_atlas_audit_events_created_at on atlas_wiki.audit_events(created_at);
